### ISSUE TITLE
09-14 02:15:34.145: W/System.err(1704): java.lang.NullPointerException 09-14 02:15:34.145: W/System.err(1704): 	at org.ksoap2.serialization.SoapSerializationEnvelope.getResponse(SoapSerializationEnvelope.java:570) 09-14 02:15:34.155: W/System.err(1704): 	at com.example.cunsapp5.CallSoap.Call1(CallSoap.java:160) 09-14 02:15:34.155: W/System.err(1704): 	at com.example.cunsapp5.Caller.run(Caller.java:30)

### ISSUE THREAD

**Issue by sahiltaneja23** [simpligility/ksoap2-android#73]

**Comment by mosabua** [comment]
Please update this issue following the instruction on our site http://simpligility.github.io/ksoap2-android/report-issue.html and reopen when you have done so.
