### ISSUE TITLE
Timeout not respected with unreachable IPs

### ISSUE THREAD

**Issue by nicolabeghin** [simpligility/ksoap2-android#82]
Hi
I'm using ksoap-3.6.0 to call SAP webservices. I got a strange behavior when timeout (2000ms) is reached, as if it wasn't respected. Any hints on why this happens? I'm testing without active connection to server (VPN not enabled) in order to check out slow/bad-performing network. I'm using IP (no DNS resolution involved).

```
03-22 10:18:01.777 2324-3808/myapp I/MyAppDeskApp: Loading from SAP (qrcode 123456789), timeout 2 seconds
03-22 10:18:03.849 2324-3850/myapp D/dalvikvm: GC_FOR_ALLOC freed 2691K, 25% free 12483K/16464K, paused 16ms, total 16ms
03-22 10:18:03.909 2324-3850/myapp D/dalvikvm: GC_FOR_ALLOC freed 3203K, 28% free 11869K/16464K, paused 17ms, total 17ms
03-22 10:18:03.965 2324-3850/myapp D/dalvikvm: GC_FOR_ALLOC freed 3055K, 28% free 11867K/16464K, paused 12ms, total 12ms
03-22 10:18:04.009 2324-3850/myapp D/dalvikvm: GC_FOR_ALLOC freed 3054K, 28% free 11867K/16464K, paused 11ms, total 11ms
03-22 10:18:04.049 2324-3850/myapp D/dalvikvm: GC_FOR_ALLOC freed 3053K, 28% free 11867K/16464K, paused 11ms, total 11ms
03-22 10:18:04.097 2324-3850/myapp D/dalvikvm: GC_FOR_ALLOC freed 3053K, 28% free 11867K/16464K, paused 13ms, total 13ms
03-22 10:18:04.145 2324-3850/myapp D/dalvikvm: GC_FOR_ALLOC freed 3053K, 28% free 11867K/16464K, paused 12ms, total 12ms

[ad libitum]

03-22 11:20:58.401 7042-7309/MyApp E/MyAppDeskApp: Error: sendto failed: ETIMEDOUT (Connection timed out)
03-22 11:20:58.401 7042-7309/MyApp W/System.err: java.net.SocketException: sendto failed: ETIMEDOUT (Connection timed out)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:468)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.splunk.mint.network.io.OutputStreamMonitor.write(OutputStreamMonitor.java:54)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.io.BufferedOutputStream.flushInternal(BufferedOutputStream.java:185)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:85)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpTransport.flushRequest(HttpTransport.java:107)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:642)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.altevie.MyApp.deskapp.UsersActivity$TestTask.doInBackground(UsersActivity.java:229)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at com.altevie.MyApp.deskapp.UsersActivity$TestTask.doInBackground(UsersActivity.java:214)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at java.lang.Thread.run(Thread.java:841)
03-22 11:20:58.401 7042-7309/MyApp W/System.err: Caused by: libcore.io.ErrnoException: sendto failed: ETIMEDOUT (Connection timed out)
03-22 11:20:58.401 7042-7309/MyApp W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
03-22 11:20:58.405 7042-7309/MyApp W/System.err:     at libcore.io.Posix.sendto(Posix.java:156)
03-22 11:20:58.405 7042-7309/MyApp W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
03-22 11:20:58.405 7042-7309/MyApp W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:466)
03-22 11:20:58.405 7042-7309/MyApp W/System.err: 	... 19 more
```

**Comment by nicolabeghin** [comment]
I isolated the issue. It seems like it's an Android bug (I'm on 4.4.4). The following AsyncTask generates the loop as the one reported above.

```java
private class TestTask extends AsyncTask<String, Void, String> {
	@Override
	protected void onPreExecute() {
		super.onPreExecute();
	}

	@Override
	protected String doInBackground(String... qrcodes) {
		try {
			URL url = new URL("http://217.19.150.253:80"); // "http://wwww.goooooooooooeoeoeoeoel.com"
			HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
			urlConnection.setConnectTimeout(4000);
			urlConnection.setReadTimeout(4000);
			try {
				Log.i(MainActivity.AppName, "starting connection to "+url.toString());
				InputStream in = new BufferedInputStream(urlConnection.getInputStream());
				Log.i(MainActivity.AppName, "Succesfully connected to "+url.toString());
			}
			catch(Exception ex) {
				Log.e(MainActivity.AppName, "Error: " + ex.getMessage());
				ex.printStackTrace();
			} finally {
				urlConnection.disconnect();
			}
		} catch (Exception e) {
			Log.e(MainActivity.AppName, "Exception in Task: " + e.getMessage());
		}
		return null;
	}
}
```

**Comment by nicolabeghin** [comment]
I can confirm it works on 5.x onwards. So it's something related to older Android releases.

**Comment by nicolabeghin** [comment]
Same behavior on Android 5.x

```
03-22 08:58:24.989 23850-28656/MyApp I/MyAppDeskApp: starting connection to http://217.19.150.253:80
03-22 08:58:38.001 23850-23863/MyApp I/art: WaitForGcToComplete blocked for 5.506ms for cause HeapTrim
03-22 08:58:42.142 23850-23859/MyApp W/art: Suspending all threads took: 8.897ms
03-22 08:58:58.243 23850-23863/MyApp I/art: WaitForGcToComplete blocked for 14.293ms for cause HeapTrim
03-22 08:59:01.183 23850-23859/MyApp W/art: Suspending all threads took: 7.088ms
03-22 08:59:05.190 23850-23859/MyApp W/art: Suspending all threads took: 7.547ms
03-22 08:59:12.741 23850-23859/MyApp W/art: Suspending all threads took: 6.325ms
03-22 08:59:18.094 23850-23864/MyApp I/art: Background sticky concurrent mark sweep GC freed 90659(5MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 14MB/19MB, paused 27.933ms total 67.373ms
03-22 08:59:20.704 23850-23864/MyApp I/art: Background sticky concurrent mark sweep GC freed 90920(5MB) AllocSpace objects, 0(0B) LOS objects, 31% free, 13MB/19MB, paused 5.673ms total 43.771ms
03-22 08:59:22.323 23850-23864/MyApp I/art: Background sticky concurrent mark sweep GC freed 92341(5MB) AllocSpace objects, 0(0B) LOS objects, 31% free, 13MB/19MB, paused 8.557ms total 18.481ms
03-22 08:59:39.141 23850-23859/MyApp W/art: Suspending all threads took: 14.690ms
03-22 08:59:55.809 23850-23859/MyApp W/art: Suspending all threads took: 10.596ms
03-22 09:00:05.789 23850-23859/MyApp W/art: Suspending all threads took: 6.416ms
03-22 09:00:15.628 23850-23864/MyApp I/art: Background sticky concurrent mark sweep GC freed 88653(5MB) AllocSpace objects, 0(0B) LOS objects, 29% free, 13MB/19MB, paused 20.685ms total 32.408ms
03-22 09:00:32.317 23850-28656/MyApp E/MyAppDeskApp: Error: sendto failed: ETIMEDOUT (Connection timed out)
```

**Comment by mosabua** [comment]
So if its an Android bug in the HTTP/Network stack... there is nothing we can really do from this project..

**Comment by nicolabeghin** [comment]
Exactly. If you're interested we're discussing about this in [https://github.com/gotev/android-host-monitor/issues/2](https://github.com/gotev/android-host-monitor/issues/2)

**Comment by gotev** [comment]
@mosabua there is a thing which you can do, and is to make your library independent from the `HttpUrlConnection` classes. This can be accomplished by wrapping all the network calls in some classes which implements a common interface, so you can later re-implement them using a different network stack underneath. It's the same I'm doing in gotev/android-upload-service#95
As I don't know the internals of your library, I don't know how much effort it requires, but it will be a huge benefit for sure, as if you use OkHttp for example, you will have the same networking behaviour on all the Android versions that you support. However, that's just a suggestion.

**Comment by mosabua** [comment]
I would love to be able to do that but I dont have the resources to work on that. I would take pull requests that implement that however..

**Comment by gotev** [comment]
@mosabua I understand you, I'm in the exactly same situation at the moment :cry:

**Comment by nicolabeghin** [comment]
I'll take a look at ksoap2 sources in order to assess if it's feasible to use `OkHttp`'s `UrlConnection `implementation.

**Comment by gotev** [comment]
@nicolabeghin beware that OkHttp's `HttpUrlConnection` support is [planned to be removed](http://square.github.io/okhttp/3.x/okhttp-urlconnection/okhttp3/OkUrlFactory.html) so as I wrote in my previous post, what I think is the best to do is to create an abstraction layer over the networking classes, to be able to easily switch implementations. That is going to make the library easily testable without a real connection, too.

**Comment by robocik** [comment]
In ksoap2 there are some abstractions related with networking. Main class HttpTransportSE is using HttpUrlConnection via ServiceConnection interface. But also there is another transport class NtlmTransport which doesn't use HttpUrlConnection. Instead it use HttpClient (to perform NTLM authentication). So probably to implement OkHttp connection, you should create another Transport class (maybe you can try to create only ServiceConnection but can't say if this will work)

**Comment by nicolabeghin** [comment]
As a quick-and-dirty workaround I'll try switching `HttpUrlConnection` reference in `ServiceConnectionSE` to the `OkHttp` version.

**Comment by robocik** [comment]
I think that probably the safer option from compatibility points of view is to implement OkHttp version as a new Transport class instead of replacing HttpUrlConnection in HttpTransportSE. For me it is hard to predict if new version will work exactly the same as old Transport class and we don't want to break all existing applications.
If you have finish this, I can test this new solution in our test enviroment (in easywsdl.com we have dozen of different tests which can be used to check if ksoap2 library still works)

**Comment by nicolabeghin** [comment]
thanks @robocik. That's exactly what I'm trying right now (`OkHttpServiceConnectionSE` and `OkHttpTransportSE`), but being unable to compile the `ksoap2-android` library in Android Studio (I see it's still not gradle-compliant) I had to work on the `createTransport` call itself (outside of `ksoap2` library). If that works ok I'll be more than happy to send you the two new classes.

**Comment by nicolabeghin** [comment]
I confirm that as suggested by @gotev using `OkHttp`'s `URLConnection` implementation the timeouts work as expected. Here's the updated test task.

 ```java
private class TestTask extends AsyncTask<String, Void, String> {
        @Override
        protected void onPreExecute() {
            super.onPreExecute();
        }

        @Override
        protected String doInBackground(String... qrcodes) {
             // "http://wwww.goooooooooooeoeoeoeoel.com"
            long timeout = 2000;
            URL url = null;
            try {
                url = new URL("http://217.19.150.253:80");
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
            OkHttpClient client = new OkHttpClient.Builder()
                    .connectTimeout(timeout, TimeUnit.MILLISECONDS)
                    .readTimeout(timeout, TimeUnit.MILLISECONDS)
                    .build();
            HttpURLConnection urlConnection = new HttpURLConnectionImpl(url, client);
            urlConnection.setConnectTimeout((int) timeout);
            urlConnection.setReadTimeout((int) timeout);
            try {
                try {
                    Log.i(MainActivity.AppName, "starting connection to "+url.toString());
                    InputStream in = new BufferedInputStream(urlConnection.getInputStream());
                    Log.i(MainActivity.AppName, "Succesfully connected to "+url.toString());
                }
                catch(Exception ex) {
                    Log.e(MainActivity.AppName, "Error: " + ex.getMessage());
                    ex.printStackTrace();
                } finally {
                    if (urlConnection!=null) {
                        urlConnection.disconnect();
                    }
                }
            } catch (Exception e) {
                Log.e(MainActivity.AppName, "Exception in Task: " + e.getMessage());
            }
            return null;
        }
    }
}
```

Outcome:
```
03-29 13:08:58.656 19027-20442/test I/TestApp: starting connection to http://217.19.150.253:80
03-29 13:09:10.728 19027-20442/test W/System.err: java.net.SocketTimeoutException: timeout
```

**Comment by nicolabeghin** [comment]
Here's the updated `OkHttpTransportSE` and `OkHttpServiceConnectionSE`

```java
package com.deskapp.utils.networking;

import org.ksoap2.HeaderProperty;
import org.ksoap2.transport.ServiceConnection;
import org.ksoap2.transport.ServiceConnectionSE;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.Proxy;
import java.net.URL;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import okhttp3.OkHttpClient;
import okhttp3.internal.huc.HttpURLConnectionImpl;

/**
 * Created by nbeghin on 29/03/2016.
 */
public class OkHttpServiceConnectionSE implements ServiceConnection {
    private HttpURLConnection connection;
    private OkHttpClient client;

    /**
     * Constructor taking the url to the endpoint for this soap communication
     * @param url the url to open the connection to.
     * @throws IOException
     */
    public OkHttpServiceConnectionSE(String url) throws IOException {
        this(null, url, ServiceConnection.DEFAULT_TIMEOUT);
    }

    public OkHttpServiceConnectionSE(Proxy proxy, String url) throws IOException {
        this(proxy, url, ServiceConnection.DEFAULT_TIMEOUT);
    }

    /**
     * Constructor taking the url to the endpoint for this soap communication
     * @param url the url to open the connection to.
     * @param timeout the connection and read timeout for the http connection in milliseconds
     * @throws IOException                            // 20 seconds
     */
    public OkHttpServiceConnectionSE(String url, int timeout) throws IOException {
        this(null, url, timeout);
    }

    public OkHttpServiceConnectionSE(Proxy proxy, String url, int timeout) throws IOException {
        client = new OkHttpClient.Builder()
                .connectTimeout(timeout, TimeUnit.MILLISECONDS)
                .readTimeout(timeout, TimeUnit.MILLISECONDS)
                .build();
        connection = new HttpURLConnectionImpl(new URL(url), client);
//        connection = (proxy == null)
//                ? new HttpURLConnectionImpl(new URL(url), client)
//                : (HttpURLConnectionImpl) new URL(url).openConnection(proxy);
        connection.setUseCaches(false);
        connection.setDoOutput(true);
        connection.setDoInput(true);
        connection.setConnectTimeout(timeout);
        connection.setReadTimeout(timeout); // even if we connect fine we want to time out if we cant read anything..
    }

    public void connect() throws IOException {
        connection.connect();
    }

    public void disconnect() {
        connection.disconnect();
    }

    public List getResponseProperties() throws IOException {
        List retList = new LinkedList();

        Map properties = connection.getHeaderFields();
        if(properties != null) {
            Set keys = properties.keySet();
            for (Iterator i = keys.iterator(); i.hasNext();) {
                String key = (String) i.next();
                List values = (List) properties.get(key);

                for (int j = 0; j < values.size(); j++) {
                    retList.add(new HeaderProperty(key, (String) values.get(j)));
                }
            }
        }

        return retList;
    }

    public int getResponseCode() throws IOException {
        return connection.getResponseCode();
    }

    public void setRequestProperty(String string, String soapAction) {
        connection.setRequestProperty(string, soapAction);
    }

    public void setRequestMethod(String requestMethod) throws IOException {
        connection.setRequestMethod(requestMethod);
    }

    /**
     * If the length of a HTTP request body is known ahead, sets fixed length
     * to enable streaming without buffering. Sets after connection will cause an exception.
     *
     * @param contentLength the fixed length of the HTTP request body
     * @see http://developer.android.com/reference/java/net/HttpURLConnection.html
     **/
    public void setFixedLengthStreamingMode(int contentLength) {
        connection.setFixedLengthStreamingMode(contentLength);
    }

    public void setChunkedStreamingMode() {
        connection.setChunkedStreamingMode(0);
    }

    public OutputStream openOutputStream() throws IOException {
        return connection.getOutputStream();
    }

    public InputStream openInputStream() throws IOException {
        return connection.getInputStream();
    }

    public InputStream getErrorStream() {
        return connection.getErrorStream();
    }

    public String getHost() {
        return connection.getURL().getHost();
    }

    public int getPort() {
        return connection.getURL().getPort();
    }

    public String getPath() {
        return connection.getURL().getPath();
    }
}

```

```java
package com.deskapp.utils.networking;

import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.ServiceConnection;

import java.io.IOException;
import java.net.Proxy;

/**
 * Created by nbeghin on 29/03/2016.
 */
public class OkHttpTransportSE extends HttpTransportSE {
    public OkHttpTransportSE(Proxy proxy, String url) {
        super(proxy, url);
    }

    public OkHttpTransportSE(Proxy proxy, String url, int timeout) {
        super(proxy, url, timeout);
    }

    public OkHttpTransportSE(Proxy proxy, String url, int timeout, int contentLength) {
        super(proxy, url, timeout, contentLength);
    }

    public OkHttpTransportSE(String url) {
        super(url);
    }

    public OkHttpTransportSE(String url, int timeout) {
        super(url, timeout);
    }

    public OkHttpTransportSE(String url, int timeout, int contentLength) {
        super(url, timeout, contentLength);
    }

    @Override
    public ServiceConnection getServiceConnection() throws IOException {
        return new OkHttpServiceConnectionSE(proxy, url, timeout);
    }
}

```

**Comment by robocik** [comment]
Currently we are busy with easywsdl bug but I will test these new classes in few days and inform about the results. But only looking on these classes, I like the idea to reuse HttpTransportSE class (as a base class). Good job!

**Comment by nicolabeghin** [comment]
Good! Please consider those classes a very simple workaround, I did not handle the proxy part (it's commented out).

**Comment by mosabua** [comment]
@nicolabeghin could you submit a PR with that?

**Comment by nicolabeghin** [comment]
hi @mosabua I would like to but I wasn't able to import the project sources on Android Studio nor Eclipse. Being ksoap2 still not gradle-based I tried setting up my old Eclipse ADT environment but the project wasn't imported correctly ("File -> Import -> Maven project", while "Android existing sources" doesn't work at all).

**Comment by mosabua** [comment]
Its a standard layout Maven project with to customs setup or dependency on Android at all. It should easily work in Eclipse or IntelliJ..  but if that fails I can create a PR in a whole from the source you copied here if thast okay. Whats the okhttp version you used?

**Comment by nicolabeghin** [comment]
I managed to import it. Pull request created #83

**Comment by mosabua** [comment]
This is now merged into master. I can merge more improvements if you got any or cut a new release. Up to you guys ..
